name: Test SDK

on:
  pull_request:
    paths:
      - '**/*'

  workflow_dispatch:

  workflow_call:
    inputs:
      test_data_branch:
        type: string
        description: The branch in sdk-test-data to target for testcase files
        required: false
        default: main
      sdk_branch:
        type: string
        description: The branch of the SDK to test
        required: false  

env:
  SDK_BRANCH_NAME: ${{ inputs.sdk_branch  || github.head_ref || github.ref_name || 'main' }}
  TEST_DATA_BRANCH_NAME: ${{ inputs.test_data_branch || 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: g++
            package: g++
            cxx: g++
            cc: gcc
          - name: clang++
            package: clang
            cxx: clang++
            cc: clang

    name: Build with ${{ matrix.compiler.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || 'Eppo-exp/cpp-sdk' }}
          ref: ${{ env.SDK_BRANCH_NAME }}

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ${{ matrix.compiler.package }}

      - name: Build library
        env:
          CXX: ${{ matrix.compiler.cxx }}
          CC: ${{ matrix.compiler.cc }}
        run: make build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || 'Eppo-exp/cpp-sdk' }}
          ref: ${{ env.SDK_BRANCH_NAME }}
          
      - name: Verify version consistency
        run: ./scripts/check-version-consistency.sh

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Run tests
        run: make test branchName=${{env.TEST_DATA_BRANCH_NAME}}

  memory-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || 'Eppo-exp/cpp-sdk' }}
          ref: ${{ env.SDK_BRANCH_NAME }}
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Run memory tests
        run: make test-memory
